common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    #회원정보관리
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change/', views.change, name='change'),
    path('mypage/', views.mypage, name='mypage'),

    #초록점수
    path('point/', views.point, name='point'),
    path('greenpoint/', views.greenpoint, name='greenpoint'),
    path('points_list/', views.points_list, name='points_list'),
    path('quiz/', views.quiz, name='quiz'),
    path('event/', views.event, name='event'),
    path('coupon/', views.coupon, name='coupon'),

    #제안하기
    path('contact/', views.contact, name='contact'),
    path('contact_point/', views.contact_point, name='contact_point'),
    path('my_contact/', views.my_contact, name='my_contact'),

    path('report/', views.report, name='report'), #경민 이것도 추가

    #관리자페이지
    path('admin/', views.admin, name='admin'),
    
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mapdata import views

urlpatterns = [
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('admin/', admin.site.urls, name='admin'),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('mapdata/', include('mapdata.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path

    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    # path('', views.index, name='index'),

    path('tip/', views.tip, name='tip'),
    path('tip/plastic/' ,views.plastic, name='plastic'),
    path('tip/glass/' ,views.glass, name='glass'),
    path('tip/balpo/' ,views.balpo, name='balpo'),
    path('tip/vinyl/' ,views.vinyl, name='vinyl'),
    path('tip/paper/' ,views.paper, name='paper'),
    path('tip/can/' ,views.can, name='can'),


    # notice 
    path('notice/', views.notice, name='notice'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('error/', views.error, name='error'),

    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),

    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

templates/includes/(temp)footer.html
{% load static %}
<section>
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdn2.hubspot.net/hub/322787/hub_generated/style_manager/1440007714979/custom/page/hack-a-thon-3/masonry.min.min.js"></script> -->
  <!-- <script src="https://cdn2.hubspot.net/hub/322787/hub_generated/style_manager/1440007849180/custom/page/hack-a-thon-3/isotope.min.js"></script> -->
  <script type="text/javascript">
    particlesJS.load('particles-js', "{% static 'text/particlesjs-config.json' %}", function() {
      console.log('callback - particles.js config loaded');
    });
  </script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/masonry.min.min.js' %}"></script>
  <script src="{% static 'js/isotope.min.js' %}"></script>

  <!------ Include the above in your HEAD tag ---------->

  <!-- Footer -->
  <nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-center">
  	<footer class="text-center footer">
      <div class="container noBot">
  			<div class="row">
  					<ul class="list-unstyled list-inline social">
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-facebook fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-twitter fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-instagram fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-google-plus fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="mailto:_______@gmail.com" target="_blank"><i class="fa fa-envelope fa-2x"></i></a></li>
  					</ul>
  			</div>
  			<div class="row">
  				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-white footer-text">
  					<p><a class="text-primary" href="{% url 'common:contact' %}">Any Suggestions?</a> 소중한 의견을 기다립니다.</p>
  					<p class="h6">&copy 2021<a class="text-white ml-2" href="{% url 'common:admin' %}" style="text-decoration:none" target="_blank">ESG Warrior</a> All right Reserved.</p>
  				</div>
  			</div>
      </div>
  	</footer>
</section>

templates/includes/_faq.html
{% load i18n %}

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#apply"><strong>{% trans "Q: 초록점수는 어떻게 받나요?" %}</strong></a>
        </div>
        <div id="apply" class="panel-collapse collapse">
            <div class="panel-body">
                <p>
                    {% blocktrans trimmed %}
                        A: 초록점수 페이지로..
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#too_late"><strong>{% trans "Q: 휴지통 위치가 잘못 표시된 것 같아요" %}</strong></a>
        </div>
        <div id="too_late" class="panel-collapse collapse">
            <div class="panel-body">
                <p>
                {% url 'core:newsletter' as newsletter_url %}
                    {% blocktrans trimmed %}
                        A: 지도 위의 <a href="/">지도보기</a> 마커클릭해서 신고
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#coach_sponsor"><strong>{% trans "Q: 휴지통 추가 설치가 필요해요" %}</strong></a>
        </div>
        <div id="coach_sponsor" class="panel-collapse collapse">
            <div class="panel-body">
                <p>{% trans "A: 아래에 써주시면 반영을 위해서 노력하겠습니다" %}</p>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#tutorial"><strong>{% trans "Q: 좋은 아이디어가 있어요" %}</strong></a>
        </div>
        <div id="tutorial" class="panel-collapse collapse">
            <div class="panel-body">
                <p>
                    {% blocktrans trimmed %}
                        A: 기다리고 있어요!!
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>
</div>

templates/includes/_field.html
<label>
    {{ field.label|safe }}
    {% if field.field.required %}<span class="required">*</span>{% endif %}
  </label>
  
  {% if field.field.help_text %}
    <p class="help-text">{{ field.field.help_text|safe }}</p>
  {% endif %}
  
  {% if field.errors %}
    {% for error in field.errors %}
    <p class="error">{{ error }}</p>
    {% endfor %}
  {% endif %}
  
  <div class="field{% if field.errors %} with-errors{% endif %}">
    {{ field }}
  </div>

templates/includes/_info_messages.html
{% for message in messages %}
<div class="alert alert-info alert-dismisable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}

templates/includes/footer.html
{% load static %}
<section>
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdn2.hubspot.net/hub/322787/hub_generated/style_manager/1440007714979/custom/page/hack-a-thon-3/masonry.min.min.js"></script> -->
  <!-- <script src="https://cdn2.hubspot.net/hub/322787/hub_generated/style_manager/1440007849180/custom/page/hack-a-thon-3/isotope.min.js"></script> -->
  <script type="text/javascript">
    particlesJS.load('particles-js', "{% static 'text/particlesjs-config.json' %}", function() {
      console.log('callback - particles.js config loaded');
    });
  </script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/masonry.min.min.js' %}"></script>
  <script src="{% static 'js/isotope.min.js' %}"></script>

  <!------ Include the above in your HEAD tag ---------->

  <!-- Footer -->
  <nav class="navbar fixed-bottom navbar-dark navbar-expand-md bg-dark justify-content-center">
  	<footer class="text-center footer">
      <div class="container noBot">
  			<div class="row">
  				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-white footer-text p-0">
  					<p style="line-height: 20%;"><a class="text-primary" href="{% url 'common:contact' %}">Any Suggestions?</a> 소중한 의견을 기다립니다.</p>
  					<p class="h8" style="line-height: 90%;">&copy 2021<a class="text-white ml-2" href="{% url 'common:admin' %}" style="text-decoration:none" target="_blank">ESG Warrior</a> All rights Reserved.</p>
  				</div>
          <div class="row">
  					<ul class="list-unstyled list-inline social">
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-facebook fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.twitter.com/trashtongtong"><i class="fa fa-twitter fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-instagram fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="https://www.instagram.com/trashtongtong"><i class="fa fa-google-plus fa-2x"></i></a></li>
  						<li class="list-inline-item"><a href="mailto:_______@gmail.com" target="_blank"><i class="fa fa-envelope fa-2x"></i></a></li>
  					</ul>
  			</div>
  			</div>
      </div>
  	</footer>
</section>

templates/includes/head.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>휴지통을 찾아서</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">

  <script src="{% static 'js/particles.min.js' %}"></script>

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"> -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script> -->

</head>

templates/includes/header.html
<nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-center">
    <a href="/" class="navbar-brand mr-0">TrashTongTong </a>
    <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
        <ul class="navbar-nav mx-auto text-center">
            <div id="notice">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'pybo:notice' %}">공지사항</a>
              </li>
            </div>
            <div id="tip">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'pybo:tip' %}">재활용팁</a>
              </li>
            </div>
            <div id="point">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'common:greenpoint' %}">초록점수</a>
              </li>
            </div>
            <div id="event">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:event' %}">EVENT</a>
                </li>
              </div>
            <div id="MyPage">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:mypage' %}">MyPage</a>
                </li>
              </div>

            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'common:logout' %}"><b class='text-info'style='font-weight:bold;'>{{ user.username }}</b>(logout)</a>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'common:login' %}">Login</a>
            {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'common:signup' %}">Signup</a></li> {% endcomment %}
            {% endif %}
        </ul>
        <ul class="nav navbar-nav flex-row justify-content-center flex-nowrap">
            <li class="nav-item"><a class="nav-link" href="https://www.instagram.com/trashtongtong"><i class="fa fa-instagram"></i></a> </li>
            <li class="nav-item"><a class="nav-link" href="mailto:______@gmail.com"><i class="fa fa-envelope"></i></a> </li>
        </ul>
    </div>
</nav>