common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    #회원정보관리
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change/', views.change, name='change'),
    path('mypage/', views.mypage, name='mypage'),

    #초록점수
    path('point/', views.point, name='point'),
    path('greenpoint/', views.greenpoint, name='greenpoint'),
    path('points_list/', views.points_list, name='points_list'),
    path('quiz/', views.quiz, name='quiz'),
    path('event/', views.event, name='event'),
    path('coupon/', views.coupon, name='coupon'),

    #제안하기
    path('contact/', views.contact, name='contact'),
    path('contact_point/', views.contact_point, name='contact_point'),
    path('my_contact/', views.my_contact, name='my_contact'),

    path('report/', views.report, name='report'), #경민 이것도 추가

    #관리자페이지
    path('admin/', views.admin, name='admin'),
    
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mapdata import views

urlpatterns = [
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('admin/', admin.site.urls, name='admin'),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('mapdata/', include('mapdata.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path

    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    # path('', views.index, name='index'),

    path('tip/', views.tip, name='tip'),
    path('tip/plastic/' ,views.plastic, name='plastic'),
    path('tip/glass/' ,views.glass, name='glass'),
    path('tip/balpo/' ,views.balpo, name='balpo'),
    path('tip/vinyl/' ,views.vinyl, name='vinyl'),
    path('tip/paper/' ,views.paper, name='paper'),
    path('tip/can/' ,views.can, name='can'),


    # notice 
    path('notice/', views.notice, name='notice'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('error/', views.error, name='error'),

    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),

    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Point, Contact, Report
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


# ID = username
# 이름(닉네임) = first_name
# 연락처 = last_name

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    last_name = forms.IntegerField(label="phone")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("phone", 'email', 'greenpoint',)

class PointForm(forms.ModelForm):
    class Meta:
        model = Point
        fields = ('reason',)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("email", "content", 'imgs')

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ("email", "content", 'imgs')
        # select = forms.CharField(widget=forms.Select(choices=TYPE_CHOICES))
        

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm, ProfileForm, PointForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib.auth.models import User
from common.models import Profile, Point, Contact, Photo, Report
from common.forms import PointForm, ContactForm, ReportForm

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('common:mypage')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


# def update_profile(request, user_id):
#     user = User.objects.get(pk=user_id)
#     user.profile.greenpoint = 0
#     user.save()


@login_required(login_url='common:login')
def change(request):
    """
    정보변경
    """
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user = user_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, ('회원정보가 변경되었습니다!'))
            return redirect('common:mypage')
        else:
            messages.warning(request, ('입력 정보를 다시 한번 확인해 주세요.'))
            update_session_auth_hash(request, user_form)            
    else:
        user_form = UserForm(instance=request.user)
    return render(request, 'common/change.html', {'user_form': user_form})


def greenpoint(request):
    return render(request, 'common/point/greenpoint.html')

def quiz(request):
    return render(request, 'common/point/quiz.html')

def event(request):
    return render(request, 'common/event.html')

monthRef = {
    8 : 'August',
    9 : 'September',
    10 : "October",
    11 : "November",
    12 : 'December',
    1 : 'January',
    2 : 'February',
    3 : 'March',
    4 : 'April',
    5 : 'May',
    6 : 'June'
}

def getStatus(v):
    if v < 10:
        return ['inactive', 'text-danger']
    elif v < 20:
        return ['average', 'text-warning']
    elif v < 30:
        return ['good', 'text-info']
    else:
        return ['spectacular', 'text-success']


# 마이페이지 (초록점수현황 포함)
@login_required(login_url='common:login')
def mypage(request):        
    userid = request.user.id
    user = User.objects.get(id=userid)

    totalPoints = user.profile.greenpoint
    couponPoints = 100
    if totalPoints >= 100:
        totalPoints = couponPoints

    pointArr = Point.objects.filter(owner_id=userid).order_by('date')

    point_sum = 0
    for point in pointArr:
        point_sum += point.point

    startMonth = pointArr.first().date.month
    endMonth = pointArr.last().date.month
    if endMonth <= 6:
        endMonth += 12
    lenn = endMonth - startMonth + 1
    points = [0]*lenn
    months = [""]*lenn
    colors = [""]*lenn
    for i in range(lenn):
        for x in pointArr:
            month = x.date.month
            if (month <= 6):
                month += 12
            if (month == startMonth + i):
                points[i] += x.point
        month = startMonth + i
        if (month > 12):
            month -= 12
        months[i] = monthRef[month]
        if points[i] < 10:
            colors[i] = "rgba(255, 99, 132,"
        elif points[i] < 20:
            colors[i] = "rgba(255, 206, 86,"
        elif points[i] < 30:
            colors[i] = "rgba(54, 162, 235,"
        else:
            colors[i] = "rgba(129, 247, 173,"

    avgPoints = (sum(points)/len(points))
    recentPoints = points[-1]
    avgStatus, avgColor = getStatus(avgPoints)[0], getStatus(avgPoints)[1]
    recentStatus, recentColor = getStatus(recentPoints)[0], getStatus(recentPoints)[1]
    avgPoints /= 40
    recentPoints /= 40
    avgPoints *= 100
    recentPoints *= 100

    context = {
        'couponPoints' : couponPoints,
        'totalPoints' : totalPoints,
        'user' : user,
        'pointArr' : pointArr,
        'months' : months,
        'points' : points,
        'colors' : colors,
        'avgPoints' : avgPoints,
        'recentPoints' : recentPoints,
        'avgStatus' : avgStatus,
        'recentStatus' : recentStatus,
        'avgColor' : avgColor,
        'recentColor' : recentColor
    }
    print(context)
    return render(request, 'common/mypage.html', context)


# 포인트 랭킹
def points_list(request):
    toplist = []
    users = User.objects.all()
    points = Profile.objects.all().order_by("-greenpoint")
    for i in range(len(points)):
        for j in range(len(users)):
            if points[i].id == users[j].id:
                toplist.append(users[j])
    context = {
        'users' : users,
        'topusers' : toplist[:10]
    }
    return render(request, 'common/point/points_list.html', context)


# 환경사랑 참여 점수받기
@login_required(login_url='common:login')
def point(request):
    user = get_object_or_404(User, pk=request.user.id)

    userid = request.user.id
    pointArr = Point.objects.filter(owner_id=userid).order_by('date')
    isvalid = 0
    for point in pointArr:
        if point.event == "1.환경사랑참여" :
            isvalid = -1
            break

    if request.method == "POST":
        form = PointForm(request.POST)
        if form.is_valid():
            if isvalid == -1 :
                messages.warning(request, '이미 참여하셨습니다.')
                return redirect('common:point')
            else:
                point = form.save(commit=False)
                point.owner = request.user
                point.date = timezone.now()
                point.point = 20
                point.reason = "환경사랑 참여 약속"
                point.event = "1.환경사랑참여"
                point.save()
                messages.info(request, '초록점수 20점을 받았습니다.')
                return redirect('common:point')
    else:
        form = PointForm()
    context = {'form': form}
    return render(request, 'common/point/points.html', context)

#제안하기
def contact(request):
    if request.user.is_authenticated:
        if(request.method == 'POST'):
            contact_form = ContactForm(request.POST)
            if contact_form.is_valid():
                post = Contact()
                post.user = request.user
                post.email = request.POST['email']
                post.subject = request.POST['subject']
                post.content = request.POST['content']
                post.create_date = timezone.datetime.now()
                try :
                    post.imgs = request.FILES['imgs']
                except :
                    pass
                post.save()
                messages.info(request, '제안이 제출되었습니다.')
                return redirect('common:my_contact')
            else :
                messages.warning(request, ('상세 내용은 필수 항목입니다.'))
        else:
            contact_form = ContactForm()
        return render(request, 'common/contact.html', {'contact_form': contact_form})
    else :
        return render(request, 'common/contact_none.html')


# 오류신고 (신고 즉시 5점 적립)
def report(request):
    if request.user.is_authenticated:
        if(request.method == 'POST'):
            report_form = ReportForm(request.POST)
            if report_form.is_valid():
                post = Report()
                post.user = request.user
                post.email = request.POST['email']
                post.content = request.POST['content']
                post.create_date = timezone.datetime.now()
                post.type = request.POST['type']
                try :
                    post.imgs = request.FILES['imgs']
                except :
                    pass
                post.save()
                point = Point()
                point.owner = request.user
                point.date = timezone.now()
                point.point = 5
                point.reason = "오류신고 참여"
                point.event = "2.오류신고 참여"
                point.save()
                messages.info(request, '참여 감사합니다. 초록점수 5점을 받으셨습니다')
                return redirect('common:report')
            else :
                messages.warning(request, ('상세 내용은 필수 항목입니다.'))
        else:
            report_form = ReportForm()
        return render(request, 'common/report.html', {'report_form': report_form})
    else :
        return render(request, 'common/report_none.html')


# 관리자페이지
def admin(request):
    if request.user.is_superuser:
        contacts = Contact.objects.all().order_by("-create_date")
        if request.method == "POST":
            contact_id = request.POST['id']
            contact = Contact.objects.get(id=contact_id)
            contact.select = 1
            contact.save()
        context = {
            'contacts' : contacts,
            }
        return render(request, 'common/admin.html', context)
    else:
        return render(request, 'pybo/index.html')

# 제안채택(사용자)
def contact_point(request):
    if request.method == "POST":
        form = PointForm(request.POST)
        point = form.save(commit=False)
        point.owner = request.user
        point.date = timezone.now()
        point.point = 20
        point.reason = "제안 채택"
        point.event = request.POST['event']
        point.save()
        contact = Contact.objects.get(id=point.event)
        contact.select = 2
        contact.save()
        messages.info(request, '초록점수 20점을 받았습니다.')
        return redirect('common:my_contact')
    else:
        form = PointForm()
    context = {'form': form }
    return render(request, 'common/my_contact.html', context)

templates/common/(temp)my_contact.html
{% extends 'layouts/default.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
  <a class="text-center">
    <h5>나의 제안하기</h5></a>
    <div class="text-right">
        </div>
    <div class="row justify-content-between my-3">
        <div class="col-2">
        </div>
    </div>
    <td><button type="submit" class="btn btn-primary">채택대기</button></td>
    제안이 접수되었고, 채택을 기다리고 있어요.<p><p>
    <td><button type="submit" class="btn btn-success">점수받기</button></td>
    제안이 채택되었어요! 버튼을 눌러서 초록점수를 받아주세요.<p>
    <td><button type="submit" class="btn btn-secondary">채택완료</button></td>
    채택 및 초록점수 받기까지 완료된 제안이에요.<p>
    <p>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th style="width:50%">내용</th>
            <th>첨부</th>
            <th>작성일시</th>
            <th>채택</th>
        </tr>
        </thead>
        <tbody>
        {% if contacts %}
        {% for contact in contacts %}
        <tr class="text-center">
            <td class="text-left">{{ contact.id }}</td>
            <td>{{ contact.subject }}</td>
            <td>{{ contact.content }}</td>
            {% if contact.imgs %}
            <td><a href="{{contact.imgs.url}}"><img src="{{contact.imgs.url}}" height="50"></a></td>
            {% else %}
            <td>None</td>
            {% endif %}
            <td>{{ contact.create_date }}</td>
            {% if contact.select == 0 %}
            <td><button type="submit" class="btn btn-primary">채택대기</button></td>
            {% elif contact.select == 1 %}
            <td><form method="post" class="post-form" action="{% url 'common:contact_point' %}">
                {% csrf_token %}
                <input type="hidden" class="form-control" name="reason" id="reason"
                value="{{ '제안 채택' |default_if_none:contact.id }}">
                <input type="hidden" class="form-control" name="event" id="event"
                value="{{ contact.id }}">
                <button type="submit" class="btn btn-success">점수받기</button>
            </form></td>
            {% else %}
            <td><button type="submit" class="btn btn-secondary">채택완료</button></td>
            {% endif %}
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">아직 나의 제안이 없어요.
                <p>소중한 의견을 기다리고 있습니다.
                <p><a href = '/common/contact'>제안하기</a>에 참여해주세요.
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

templates/common/event.html
{% extends 'layouts/default.html' %}
{% load i18n static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event</title>
    <style>
        .event {
          border: 0;
          line-height: 2.5;
          padding: 0 20px;
          font-size: 1rem;
          text-align: center;
          color: rgb(255, 255, 255);
          text-shadow: 1px 1px 1px #000;
          border-radius: 10px;
          background-color: rgba(87, 155, 70, 0.664);
          background-image: linear-gradient(to top left,
                                          rgba(0, 0, 0, .2),
                                          rgba(0, 0, 0, .2) 30%,
                                          rgba(0, 0, 0, 0));
          box-shadow: inset 2px 2px 3px rgba(255, 255, 255, .6),
                      inset -2px -2px 3px rgba(0, 0, 0, .6);
        }
        .event:hover {
            background-color: rgb(46, 155, 88);
        }
        
        @font-face {
        font-family: 'GowunDodum-Regular';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/GowunDodum-Regular.woff') format('woff');
        font-weight: normal; font-style: normal;
        }
        body {
            font-family: 'GowunDodum-Regular'; word-break: keep-all; font: size 10px;
        }
        .eventnum {
            font-weight:bold; background: linear-gradient(to top, #FFE400 50%, transparent 50%);font-size: 1.2rem;
        }
  </style>
</head>
<body>

        <div></div>
        <div class="container" style="text-align: center;">
            <section id="event">
                <div class="row">
                    <div class="col-md-12" style="margin-top: 5%;">
                        <img src="/static/image/event.png" alt = "event" style="max-width: 20%; height:auto; vertical-align: middle;">
                        <h2 style="font-weight: bold;">이벤트 참여하시고</br><a class='text-success'>초록점수</a> 받아가세요!</h2>
                    </div>
                </div>
        
                <hr>
                <div class="cover">
                    <a><img src="/static/image/1.png" alt = "event" style=" max-width: 10%; height:auto; margin: 0.2rem; ">
                    <span class="eventnum">이벤트 하나.</br></span></a>
                <h6><span>가입</span>만 하셔도 <span style="color: rgb(102, 128, 32);font-weight: bolder;">초록점수 10점</span>을 드려요.<p>
                        지금 바로 <a class href = {% url 'common:signup' %}>가입하기</a>로 가볼까요? 
                        <p><a class href = {% url 'common:signup' %}>
                            <img src="/static/image/event_1.jpg" alt = "event_1" style="max-width:60%; height:auto;">
                        <p><a class href = {% url 'common:signup' %} style="text-align: center;">
                        
                    </a>
                </div>
                <div class="info">
                    <p>
                        {% blocktrans trimmed %}
                        <span class="text-dark" style='font-weight:bold;'> <p>
                        {% endblocktrans %}
                    </p>                     
                </div>
                                <p><p>
                                </br>                    
        
                <div class="cover">
                    <img src="/static/image/2.png" alt = "event" style="max-width: 10%; height:auto; margin: 0.2rem; ">
                    <span class="eventnum">이벤트 둘.</span>
                    <h6>환경사랑 참여를 약속하시면 <span style="color: rgb(102, 128, 32);font-weight: bolder;">초록점수 20점</span>을 드립니다.<p>
                        아래의 <span style="color: rgb(30, 148, 30);">지구</span>를 클릭해서 <span>참여</span>해주세요!</h6><p>
                            <p><a class href = {% url 'common:point' %}>
                        <img src="/static/image/event_2.png" alt = "event_2" style="max-width:60%; height:auto;">
                    </a>
                </div>
                <div class="info">
                    <p>
                        {% blocktrans trimmed %}
                        <span class="text-dark" style='font-weight:bold;'> <p> 
                            
                        {% endblocktrans %}
                    </p>                     
                </div>
            
                <p></p>
                </br>
                    <div class="cover">
                        <img src="/static/image/3.png" alt = "event" style=" max-width: 10%; height:auto; margin: 0.2rem; ">
                        <span class="eventnum">이벤트 셋.</span>
                            <a class='text-secondary' style='font-weight:bold;'>[Exhibition only]</a></h5>
                        <h6>얼마나 열심히 참여하셨는지 궁금하신가요? 
                            <p>모든 회원 중 <span style="color: rgb(118, 92, 209);font-weight: bolder;">나의 초록점수 순위</span>를 확인할 수 있어요.</h6><p>
                             <a class="event" href="#!" style="text-decoration:none" input type="button" onclick=href="{% url 'common:points_list' %}">실시간 순위 확인하기</a>
                     
                    </div>
                    <div class="info">
                        <p>
                            {% comment %} <p><a class href = {% url 'common:point' %}>
                                <img src="/static/image/greenpoint.png" alt = "quiz" style="max-width:70%; height:auto;"> {% endcomment %}
                            {% blocktrans trimmed %}
                            <span class="text-dark" style='font-weight:bold;'> <p>
                            {% endblocktrans %}
                        </p>                     
                    </div>
        
                <p><p>    
        
        
                    {% comment %} <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!" 
                    style="font-size:20px; " input type="button" onclick=href="{% url 'common:points_list' %}">[EVENT]실시간 초록점수순위</a>
                
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!" 
                    style="font-size:20px";input type="button" onclick=href="{% url 'common:point' %}">초록점수받기</a>
                    </br> {% endcomment %}
        
            </div>
            </section>
        </div>
</body>
</html>
{% endblock %}

templates/common/login.html
{% extends 'layouts/default.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">회원가입을 해주세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/mypage.html
{% extends 'layouts/default.html' %}
{% load static %}
{% load mathTags %}
{% block content %}

<head>
  <script src="{% static 'js/Chart.bundle.min.js' %}"></script>
  <script src="{% static 'js/loading-bar.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/loading-bar.css' %}">
  <script src="https://cdn.jsdelivr.net/gh/emn178/chartjs-plugin-labels/src/chartjs-plugin-labels.js"></script>
 </head>

 <p>
<div class="student container">
  <div class="row">
    <div class="col">
      <div class ="student-breakdown">
        <div class= "shadow text-center">
          <div class="lineage">
            <h3><span class='text-black'>안녕하세요,
               <span class='text-black' style='font-weight:bold;'>{{ user.first_name }}</span>
              <span class='text-black'> 님!</h3>
          </div>

          <h2 style='text-align: right'>
            <a class="btn btn-light lineage" href="{% url 'common:my_contact' %}"role="button"
            aria-expanded="false" aria-controls="history">
           나의 제안
           </a>
            <a class="btn btn-light lineage" href="{% url 'common:change' %}"role="button"
             aria-expanded="false" aria-controls="history">
            회원정보변경
            </a>
           </h2>

          <table class="table table-light bg-light table-bordered table-condensed table-striped table-hover">
            <thead>
              <tr>
                <th>ID</th>
                <td>{{ user.username }}</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>이름</th>
                <td>{{ user.first_name }}</td>
              </tr>
              <tr>
                <th>연락처</th>
                <td>{{ user.last_name }}</td>
              </tr>
              <tr>
                <th>이메일</th>
                <td>{{ user.email }}</td>
              </tr>

            </tbody>
          </table>

          <p>
          {% with percent=user.profile.greenpoint|divide:totalPoints %}
          <div class ="hr-large lineage"></div>
          <h4><span class='text-black'>초록점수  </span><span class = "text-success lineage">{{ user.profile.greenpoint }} points<span class='text-black'> 를 모으셨어요.  </span></h4>
          {% endwith %}
          <a class="btn btn-success lineage" href="{% url 'common:coupon' %}"role="button"
          aria-expanded="false" aria-controls="history">
          나의 에코쿠폰 {{ user.profile.coupon }}매
         </a>
          

        {% comment %} <form method="post" class="post-form" action="{% url 'common:mypage' %}">
            {% csrf_token %}
            <input type="hidden" class="form-control" name="reason" id="reason"
            value="{{ '제안 채택' |default_if_none:contact.id }}">
            <input type="hidden" class="form-control" name="event" id="event"
            value="{{ '4.쿠폰교환' }}">
            <button type="submit" class="btn btn-success">점수받기</button>
        </form>  {% endcomment %}

          <div class="collapsable spacedCol text-left">
              <p style='text-align: right'>
              <a class="btn btn-dark lineage" data-toggle="collapse" href="#history" role="button" 
              aria-expanded="false" aria-controls="history">
                적립내역상세
              </a>
            </p>
            <div class="collapse" id="history">
              <div class="card card-body bg-dark">
                {% for entry in pointArr %}
                <div class="row">
                    <div class="col">
                      <p><span class="text-success" style='font-weight:bold;'>{{ entry.point }} points</span> <span class='text-white'>from {{ entry.reason }} on {{ entry.date }}</span></p>
                    </div>
                </div>
                {% endfor %}

              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <!-- Start doughnut chart -->
              <canvas id="distChart" height="400" width="400"></canvas>
              <script type="text/javascript">
                var ctx = document.getElementById('distChart');
                var myChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: [ '나의 초록점수', "쿠폰 획득까지 남은 초록점수"],
                        datasets: [{
                            label: 'Point distribution',
                            data: [ {{ user.profile.greenpoint }}, {{ couponPoints }}-{{totalPoints}} ],
                            backgroundColor: [
                                'rgba(5, 151, 5, 0.7)',
                                'rgba(210, 216, 210, 0.2)'
                            ],
                            borderColor: [
                                'rgba(3, 48, 3, 0.8)',
                                'rgba(158, 159, 158, 0.7)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        title: {
                          display: true,
                          text: 'Point distribution'
                        },
                        responsive: true,
                        maintainAspectRatio: false,
                        pieceLabel: {
                        },
                    }
                });
              </script>
              <!-- End doughnot chart -->
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<p>
  <p>

{% endblock %}