common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    #회원정보관리
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change/', views.change, name='change'),
    path('mypage/', views.mypage, name='mypage'),

    #초록점수
    path('point/', views.point, name='point'),
    path('greenpoint/', views.greenpoint, name='greenpoint'),
    path('points_list/', views.points_list, name='points_list'),
    path('quiz/', views.quiz, name='quiz'),
    path('event/', views.event, name='event'),
    path('coupon/', views.coupon, name='coupon'),

    #제안하기
    path('contact/', views.contact, name='contact'),
    path('contact_point/', views.contact_point, name='contact_point'),
    path('my_contact/', views.my_contact, name='my_contact'),

    path('report/', views.report, name='report'), #경민 이것도 추가

    #관리자페이지
    path('admin/', views.admin, name='admin'),
    
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mapdata import views

urlpatterns = [
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('admin/', admin.site.urls, name='admin'),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('mapdata/', include('mapdata.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path

    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    # path('', views.index, name='index'),

    path('tip/', views.tip, name='tip'),
    path('tip/plastic/' ,views.plastic, name='plastic'),
    path('tip/glass/' ,views.glass, name='glass'),
    path('tip/balpo/' ,views.balpo, name='balpo'),
    path('tip/vinyl/' ,views.vinyl, name='vinyl'),
    path('tip/paper/' ,views.paper, name='paper'),
    path('tip/can/' ,views.can, name='can'),


    # notice 
    path('notice/', views.notice, name='notice'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('error/', views.error, name='error'),

    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),

    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import transaction
from django.utils import timezone
import hashlib
from django.utils.translation import gettext_lazy as _

def hashKey():
    ck = CurrentKey.objects.first()
    print(ck)
    ck.currentKey = ck.currentKey + 1
    ck.save()
    return hashlib.sha256(str(ck.currentKey).encode('utf-8')).hexdigest()

def hashUserNo(string):
    return hashlib.sha256(str(hashlib.sha256(str(string+"iwannabetheboshy").encode('utf-8')).hexdigest()+"donotdisturb").encode('utf-8')).hexdigest()


now = timezone.now()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=30, null=True)
    email = models.CharField(max_length=100, null=True)
    greenpoint = models.IntegerField('초록점수', blank=True, null=True)
    coupon = models.IntegerField('쿠폰', default = 0)

    def __str__(self):
        return self.user.username

# 유저 생성시 profile.greenpoint 생성
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.greenpoint = 10

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Point(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    point = models.IntegerField(default=0)
    reason = models.TextField(default="")
    event = models.TextField(default="")
    def __str__(self):
        return self.owner.username

@receiver(post_save, sender=User)
def create_user_points(sender, instance, created, **kwargs):
    if created:
        point = Point.objects.create(owner=instance)
        point.date = timezone.now()
        point.point = 10
        point.reason = "가입축하포인트"
        point.event = "0.가입"
        point.save()
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# 포인트 발생시 proflie.greenpoint에 반영    
@receiver(post_save, sender=Point)
def add_points(sender, instance, created, **kwargs):
    if created:
        user_id = instance.owner_id
        user = User.objects.get(id=user_id)
        pointArr = Point.objects.filter(owner_id=user_id).order_by('date')
        point_sum = 0
        for point in pointArr :
            point_sum += point.point
        user.profile.greenpoint = point_sum
        user.profile.save()
        

class Contact(models.Model):
   
    ADD, IDEA, ERROR, ETC = 'add', 'idea', 'error', 'etc'
    TYPE_CHOICES = (
        (ADD, '휴지통 추가 설치가 필요해요'),
        (IDEA, '이런 기능이 있었으면 해요'),
        (ERROR, '사이트에 오류가 있어요'),
        (ETC, '그 외 문의가 있어요')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    imgs = models.ImageField(upload_to='images/', blank=True, null=True)
    select = models.IntegerField(default=0) 
    # 0=채택전   1=채택완료,점수받기전   2=채택완료,점수받기완료
    
    type = models.CharField(
        choices=TYPE_CHOICES,
        max_length=100, null=True, blank=True)

    class Meta:
        ordering = ('-create_date',)

    def __str__(self):
        return self.subject

class Photo(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


# 경민 오류신고
class Report(models.Model):
   
    CORRECT, DELETE, ERROR, ETC = 'correct', 'delete', 'error', 'etc'
    TYPE_CHOICES = (
        (CORRECT, '재활용통이 아니라 휴지통이에요'),
        (DELETE, '휴지통이 철거되었어요'),
        (ERROR, '휴지통 위치가 조금 더 위에 있어요'),
        (ETC, '바나나 밟고 미끄러져서 아파쪄')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    imgs = models.ImageField(upload_to='images/', blank=True, null=True)
    # type = models.CharField(
    #     verbose_name=_("어떤 제안이 있으신가요?"),
    #     max_length=20,
    #     choices=CONTACT_TYPE_CHOICES,
    #     default=ADD
    # )
    type = models.CharField(
        choices=TYPE_CHOICES,
        max_length=100, null=True, blank=True)

    class Meta:
        ordering = ('-create_date',)

    def __str__(self):
        return self.subject

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>휴지통을 찾아서</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js'%}"></script>


</body>
</html>

templates/detail.html
{% for photo in contact.photo_set.all%}
    <img src="{{photo.image.url}}" width="50"><br>
{% endfor %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <div class="container-fluid">
                <button class="btn btn-primary" id="sidebarToggle">X고장X</button>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item"><a class="nav-link" href="/">HOME</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'common:logout' %}"><b style='color:green'>{{ user.username }}</b>(logout)</a>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'common:login' %}">login</a>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'common:signup' %}">signup</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">admin</a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href='http://34.64.187.150:8000/admin/'>관리자페이지</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container-fluid">
        </div>
    </div>
</div>